CREATE DATABASE IF NOT EXISTS blog_db;
USE blog_db;

DROP TABLE IF EXISTS post_label;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS writers;
DROP TABLE IF EXISTS DATABASECHANGELOG;
DROP TABLE IF EXISTS DATABASECHANGELOGLOCK;